---
name: Bug Report
about: Create a report to help us improve
title: '[BUG] '
labels: ['bug']
assignees: ['saipulimdn']

---

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Import module '...'
2. Call function '....'
3. With parameters '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Code Example**
```go
// Provide a minimal code example that reproduces the issue
package main

import "github.com/saipulimdn/gopackkit/..."

func main() {
    // Your code here
}
```

**Environment (please complete the following information):**
- OS: [e.g. Linux, macOS, Windows]
- Go Version: [e.g. 1.21.0]
- GoPackKit Version: [e.g. v0.1.0]
- Module: [e.g. logger, jwt, password]

**Error Output**
```
Paste the full error output here
```

**Additional context**
Add any other context about the problem here.
